config/routes.rb
Rails.application.routes.draw do


  root 'page#index'


  resources :video

  get 'application/:id', to: 'page#app_show', as: :application
  get 'tester/:id', to: 'page#tester_show', as: :tester
  get 'photo/:id', to: 'photo#show', as: :photo


  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]

  namespace :api do
    namespace :v1 do
      post 'record', to: 'record#create'
      post 'application/:id/video', to: 'record#upload_video'
    end
  end



end

app/models/application.rb
class Application < ActiveRecord::Base

  validates :name, presence: true
  has_many :testers

end

app/models/emotion.rb
class Emotion < ActiveRecord::Base

  belongs_to :photo
  belongs_to :video

  validates :name, presence: true
  validates :photo_id, presence: true, if: 'video_id.nil?'
  validates :video_id, presence: true, if: 'photo_id.nil?'

  validates :start, :finish, presence: true, if: 'video'

end

app/models/photo.rb
class Photo < ActiveRecord::Base


  has_many :emotions, dependent: :destroy
  belongs_to :imageable, polymorphic: true

  validates :image, :imageable_id, :imageable_type, presence: true

  accepts_nested_attributes_for :emotions, allow_destroy: true

  def emojis
    data = emotions.map(&:name)
    result = data.map do |e|
      image = Emoji.image_url_for_unicode_moji(e)
      asset_path = ActionController::Base.helpers.asset_path(image)
      ActionController::Base.helpers.image_tag(asset_path)
    end.join(' ')
    result.tr!('"', "'")
    result
  end

end

app/models/tester.rb
class Tester < ActiveRecord::Base

  belongs_to :application
  has_many :photos, as: :imageable, dependent: :destroy
  has_many :videos

  validates :name, :application_id, presence: true


end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :login, presence: true

end

app/models/video.rb
class Video < ActiveRecord::Base

  belongs_to :tester
  belongs_to :application

  has_many :emotions, dependent: :destroy

  validates :data, :application_id, :tester_id, presence: true

  accepts_nested_attributes_for :emotions, allow_destroy: true

  def emojis
    emoji_index = Emoji::Index.new
    timeline = emotions.map do |e|
      name = emoji_index.find_by_moji(e.name)['name']
      [name, e.start, e.finish]
    end
    pie = timeline.reduce({}) do |e,k|
      e[k[0]] ||= 0
      e[k[0]] += 1
      e
    end
    [timeline,pie]
  end

end

app/controllers/api/v1/record_controller.rb
require 'dropbox_sdk'

class Api::V1::RecordController < ApplicationController


  # {
  #     user_name: "",
  #     app_name: "",
  #     app_desc: "",
  #     user_desc: "",
  #     data: {
  #         images: [
  #             {
  #                 data: "",
  #                 emotions: []
  #             }
  #         ],
  #         video: [
  #             {
  #                data: "",
  #                emotions: [
  #                    {
  #                        name: ' ',
  #                        start: ' ',
  #                        finish: ' '
  #                    }
  #                ],
  #                duration: ' '
  #             }
  #         ]
  #     }
  # }

  skip_before_action :check_auth

  def create

    record = params[:record]

    app = Application.find_or_create_by(name: record[:app_name], description: record[:app_desc])
    user = Tester.find_or_create_by( application: app, name: record[:user_name], descriptions: record[:user_desc] )


    destroy_all_data(app,user)
    images = params[:data][:images]
    videos = params[:data][:videos]
    images && images.each do |image_data|
      photo = Photo.new
      emotions = image_data[:emotions]
      photo.image = image_data[:data]
      photo.imageable = user
      # photo.application = app
      photo.save

      emotions && emotions.each do |e|
        Emotion.create(name: e,photo: photo)
      end
    end
    videos && videos.each do |video_data|
      video = Video.new
      emotions = video_data[:emotions]
      video.data = video_data[:data]
      video.duration = video_data[:duration]
      video.application = app
      video.tester = user
      video.save
      emotions && emotions.each do |e|
        name = e[:name]
        start = e[:start]
        finish = e[:finish]
        Emotion.create(name: name,video: video,start: start, finish: finish)
      end

    end

    render json: {
        result: app.to_json
    }
  end

  def upload_video
    app = Application.find_by(id: params[:id])
    tester = Tester.find_by(name: params[:user_name])
    params[:videos].each do |video_data|

    end
    render json: {
        result: 'success'
    }
  end

  private

  def destroy_all_data app,user
    Photo.where(imageable: user).destroy_all
    Video.where(tester: user).destroy_all
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception


  before_action :check_auth

  def check_auth
    if current_user.nil?
      session[:load_url] = request.url
      redirect_to new_session_path
    end
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def set_current_user(user) # current_user=
    session[:user_id] = user.id
  end

end

app/controllers/page_controller.rb
class PageController < ApplicationController


  def index
    @applications = Application.all
  end

  def app_show
    @app = Application.find_by(id: params[:id])
  end

  def tester_show
    @tester = Tester.find_by(id: params[:id])
    @photos = @tester.photos
    @videos = @tester.videos
  end


end

app/controllers/photo_controller.rb
class PhotoController < ApplicationController

  def show
    photo = Photo.find_by(id: params[:id])

    data = if photo.nil? || photo.image.nil?
      File.read( 'public/404.png' )
    else
      Base64::decode64(photo.image)
    end

    send_data( data, type: 'image/png', disposition: 'inline')
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  before_action :check_auth, except: [:new, :create, :destroy]
  before_action :if_auth_redirect

  def new
  end

  def create
    user = User.find_by(login:  params[:login])
    if user && user.authenticate(params[:password])
      set_current_user(user)
      redirect_to (session.delete(:load_url) || root_path)
    else
      redirect_to new_session_path, alert: 'Проверьте логин и пароль'
    end
  end

  def destroy

  end

  private

  def if_auth_redirect
    redirect_to root_path if current_user
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :check_auth, except: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    unless @user.save
      flash[:alert] = t('flash.register.error')
      render :new and return
    end
    flash[:notice] = t('flash.register.done')
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:login, :password)
  end

end

app/controllers/video_controller.rb
class VideoController < ApplicationController

  def index
  end

  def show
    video = Video.find_by(id: params[:id])

    data = if video.nil? || video.data.nil?
             send_data( File.read( 'public/404.png'), type: 'image/png', disposition: 'inline' )
           else
             send_data( Base64::decode64(video.data), type: 'video/mp4', disposition: 'inline' )
           end


  end
  def create

  end

  def destroy

  end

  def update

  end

end

app/helpers/api/v1/record_helper.rb
module Api::V1::RecordHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type.to_sym] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} alert-dismissible", role: 'alert') do
        concat(content_tag(:button, class: 'close', data: { dismiss: 'alert' }) do
          concat content_tag(:span, '&times;'.html_safe, 'aria-hidden' => true)
          concat content_tag(:span, 'Close', class: 'sr-only')
        end)
        concat message
      end)
    end
    nil
  end

end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/photo_helper.rb
module PhotoHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/video_helper.rb
module VideoHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DiplomServer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
  <%= csrf_meta_tags %>

</head>
<body>
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">Панель администрации</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">

    </div>
  </div>
</nav>

<div class="container-fluid">
  <div class="row">
    <div class="col-sm-9 col-sm-offset-1 col-md-10 col-md-offset-1 main">
      <%= bootstrap_flash %>
      <%= yield %>
    </div>
  </div>
</div>
</body>
</html>

app/views/page/app_show.html.erb
<table class="table table-striped">
      <thead>
      <tr>
        <th>Приложение: '<%= @app.name %>'</th>
      </tr>
      <% unless @app.description.nil? %>
      <tr>
        <th>Описание: '<%= @app.description %>'</th>
      </tr>
          <% end %>
      </thead>
      <tbody>
      <% @app.testers.each do |app| %>
          <tr>
            <td><%= link_to app.name,tester_path(app) %></td>
          </tr>
      <% end %>
  </tbody>
</table>

app/views/page/index.html.erb
<table class="table table-striped">
  <% if @applications.empty? %>
    Пока приложений нету =(
  <% else %>
      <thead>
      <tr>
        <th>Приложения</th>

      </tr>
      </thead>
      <tbody>
    <% @applications.each do |app| %>
        <tr>
          <td><%= link_to app.name,application_path(app) %></td>
        </tr>
    <% end %>
  <% end %>
  </tbody>
</table>

app/views/page/login_form.erb
<div class="login_form">
  <%= form_tag login_path do %>
      <%= text_field_tag :login %>
      <%= password_field_tag :password %>
      <%= submit_tag 'Войти' %>
  <% end %>
</div>

app/views/page/tester_show.html.erb
<table class="table table-striped">
  <thead>
  <tr>
    <th>Пользователь: '<%= @tester.name %>'</th>
  </tr>
  <% unless @tester.descriptions.nil? %>
      <tr>
        <th>Описание: '<%= @tester.descriptions %>'</th>
      </tr>
  <% end %>
  <tr>
    <th>Фото</th>
  </tr>
  </thead>
  <tbody>
  <tr>
    <td>
  <% @tester.photos.each do |photo| %>
          <%= link_to '#modal', 'data-toggle': "modal" do %>
              <%= image_tag photo_path(photo), class: 'image_preview', 'data-emoji': photo.emojis  %>
          <% end %>
  <% end %>
    </td>
  </tr>
  </tbody>
</table>

<table class="table table-striped">
  <thead>
  <tr>
    <th>Видео</th>
  </tr>
  </thead>
  <tbody>
  <tr>
    <td>
  <% @tester.videos.each do |video| %>
      <%= link_to '#modal', 'data-toggle': "modal" do %>
        <%= video_tag video_path(video), class: 'video_preview', preload: 'auto', 'data-id': video.id  %>
        <div style="display: none;" id="video_<%= video.id %>" >
          <%= video.emojis.to_json %>
        </div>
      <% end %>
  <% end %>
    </td>
  </tr>
  </tbody>
</table>


<div class="modal fade" id="modal" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="image">
      </div>
      <div class="video">
        <%= video_tag '', id: 'video', controls: 'controls' %>
      </div>
      <div class="emoji">
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<% @user.errors.messages.each do |k,v| %>
  <%= k %>: <%= v%> <br>
<% end %>
<div class="login_form">

  <%= form_for @user do |f| %>
      <%= f.label :login %>
      <%= f.text_field :login %>
      <%= f.label :password  %>
      <%= f.password_field :password %>

      <%= submit_tag 'Зарегистрироватся' %>

  <% end %>

</div>

app/views/video/index.html.erb
<h1>Video#index</h1>
<p>Find me in app/views/video/index.html.erb</p>

app/views/video/show.html.erb
<h1>Video#show</h1>
<p>Find me in app/views/video/show.html.erb</p>